/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_codingmaxima_core_JudgerNativeClient */

#ifndef _Included_com_codingmaxima_core_JudgerNativeClient
#define _Included_com_codingmaxima_core_JudgerNativeClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codingmaxima_core_JudgerNativeClient
 * Method:    judge
 * Signature: (IIIIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_codingmaxima_core_JudgerNativeClient_judge
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jstring, jstring, jstring, jstring, jobjectArray, jobjectArray, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
